# Generated by Django 3.1.3 on 2020-12-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('pet_type', models.CharField(choices=[('CAT', 'кошка'), ('DOG', 'собака')], default='DOG', max_length=3, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Окрас',
                'verbose_name_plural': 'Окрасы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('CAT', 'кошка'), ('DOG', 'собака')], default='CAT', max_length=3, verbose_name='Вид')),
                ('gender', models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], default='M', max_length=1, verbose_name='Пол')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/pets/', verbose_name='Фото')),
                ('name', models.CharField(max_length=20, verbose_name='Кличка')),
                ('age', models.FloatField(default=0, verbose_name='Возраст, лет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата поступления')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Стерилизовано')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Привито')),
                ('chipped', models.BooleanField(default=False, verbose_name='Чипировано')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_breed', to='strayhome.breed', verbose_name='Порода')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_color', to='strayhome.color', verbose_name='Окрас')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ('pet_type', '-gender', 'breed__name', 'color__name', 'age'),
            },
        ),
    ]
